import React from 'react';
import { MapPin, Package, TrendingDown, Leaf, Sparkles, Zap } from 'lucide-react';
import { NearbyMarket } from '../../shared/types.ts';
import { formatINR } from '../lib/format';

interface RecommendedMarketSummaryProps {
  market: NearbyMarket;
  allMarkets: NearbyMarket[];
}

// This whole component's numbers are computed from data already fetched
// from this app's own backend (real distance/price/freshness/travel-time) —
// "AI Recommendation" labels the scoring algorithm behind them
// (server/routes/markets.routes.ts), it does not mean any of this text was
// generated by an LLM. No number here is invented.
const RecommendedMarketSummary: React.FC<RecommendedMarketSummaryProps> = ({ market, allMarkets }) => {
  const byDistance = [...allMarkets].sort((a, b) => a.distanceKm - b.distanceKm);
  const distanceRank = byDistance.findIndex((m) => m.id === market.id) + 1;
  const nextNearest = byDistance.find((m) => m.id !== market.id && m.distanceKm >= market.distanceKm);

  const byProducts = [...allMarkets].sort((a, b) => b.productCount - a.productCount);
  const productRank = byProducts.findIndex((m) => m.id === market.id) + 1;

  const byFreshness = [...allMarkets].sort((a, b) => b.avgFreshness - a.avgFreshness);
  const freshnessRank = byFreshness.findIndex((m) => m.id === market.id) + 1;

  const others = allMarkets.filter((m) => m.id !== market.id && m.avgPrice > 0);
  const othersAvgPrice = others.length > 0 ? others.reduce((s, m) => s + m.avgPrice, 0) / others.length : 0;
  const priceDeltaPct = othersAvgPrice > 0 ? Math.round(((othersAvgPrice - market.avgPrice) / othersAvgPrice) * 100) : 0;
  const priceRank = [...allMarkets].sort((a, b) => a.avgPrice - b.avgPrice).findIndex((m) => m.id === market.id) + 1;

  const reasonTags = [
    distanceRank === 1 && 'Closest',
    productRank === 1 && 'Most Stock',
    priceRank === 1 && 'Best Price',
    freshnessRank === 1 && 'Freshest',
  ].filter(Boolean) as string[];

  // The WOW stat compares against the nearest OTHER market to the user, not
  // whichever scored 2nd overall — a shopper's realistic "next-best option"
  // is a geographically plausible alternative, not just whatever ranked 2nd.
  // It's also capped to markets within a real shopping radius: with only a
  // handful of seeded markets spread across the country, the "nearest
  // other" one can still be hundreds of km away, which would produce a
  // technically-true but absurd claim ("saves you 2000+ minutes") against a
  // market no real shopper would ever cross-shop between. Below that radius
  // there's simply no meaningful "next-best option" to compare against, and
  // the banner is skipped rather than shown with a nonsense number.
  const REASONABLE_ALTERNATIVE_RADIUS_KM = 100;
  const nearestOther = byDistance.find((m) => m.id !== market.id);
  const runnerUp = nearestOther && nearestOther.distanceKm <= REASONABLE_ALTERNATIVE_RADIUS_KM ? nearestOther : null;
  const priceSavings = runnerUp ? Math.max(0, runnerUp.avgPrice - market.avgPrice) : 0;
  const timeSavings = runnerUp ? Math.max(0, runnerUp.travelTimeMins - market.travelTimeMins) : 0;

  return (
    <div className="bg-white border-4 border-neutral-900 shadow-[20px_20px_0px_0px_rgba(0,0,0,0.05)]">
      <div className="p-10 lg:p-16 space-y-10">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="space-y-2">
            <div className="badge-pulse inline-flex items-center gap-2 bg-navy-900 text-white px-4 py-1.5 text-[10px] font-black uppercase tracking-[0.4em]">
              <Sparkles size={12} /> AI Recommendation
            </div>
            <h3 className="text-4xl font-display font-black text-neutral-900 uppercase tracking-tighter leading-tight">
              {market.recommended ? `Why we recommend ${market.name}` : `${market.name} at a glance`}
            </h3>
            {reasonTags.length > 0 && (
              <div className="flex flex-wrap gap-2 pt-2">
                {reasonTags.map((tag) => (
                  <span key={tag} className="px-3 py-1 rounded-full bg-agri-50 text-agri-600 border border-agri-100 text-[9px] font-black uppercase tracking-widest">
                    {tag}
                  </span>
                ))}
              </div>
            )}
          </div>

          <div className="text-right shrink-0">
            <p className="mono-label text-neutral-400">Confidence</p>
            <div className="text-5xl font-display font-black text-agri-600 number-tabular">{market.confidenceScore}%</div>
          </div>
        </div>

        {market.recommended && runnerUp && (priceSavings > 0 || timeSavings > 0) && (
          <div className="bg-agri-600 text-white p-6 flex items-center gap-4 shadow-lg">
            <Zap size={24} className="shrink-0 fill-current" />
            <p className="text-base font-bold leading-snug">
              This market saves you {priceSavings > 0 ? `${formatINR(priceSavings)}/kg` : ''}
              {priceSavings > 0 && timeSavings > 0 ? ' and ' : ''}
              {timeSavings > 0 ? `${timeSavings} minutes` : ''} compared to {runnerUp.name}, your next-best option.
            </p>
          </div>
        )}

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="space-y-3">
            <div className="w-12 h-12 rounded-full bg-agri-50 text-agri-600 flex items-center justify-center">
              <MapPin size={20} />
            </div>
            <p className="mono-label text-neutral-400">Distance Advantage</p>
            {distanceRank === 1 && nextNearest ? (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                Closest option at {market.distanceKm} km — {Math.round((nextNearest.distanceKm - market.distanceKm) * 10) / 10} km nearer than the next closest market.
              </p>
            ) : (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                {market.distanceKm} km away — the {ordinal(distanceRank)} closest of {allMarkets.length} nearby markets.
              </p>
            )}
          </div>

          <div className="space-y-3">
            <div className="w-12 h-12 rounded-full bg-agri-50 text-agri-600 flex items-center justify-center">
              <Package size={20} />
            </div>
            <p className="mono-label text-neutral-400">Product Availability</p>
            {productRank === 1 ? (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                Widest selection nearby — {market.productCount} products from {market.vendorCount} vendors, more than any other nearby market.
              </p>
            ) : (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                {market.productCount} products from {market.vendorCount} vendors — the {ordinal(productRank)} widest selection among {allMarkets.length} nearby markets.
              </p>
            )}
          </div>

          <div className="space-y-3">
            <div className="w-12 h-12 rounded-full bg-agri-50 text-agri-600 flex items-center justify-center">
              <TrendingDown size={20} />
            </div>
            <p className="mono-label text-neutral-400">Price Advantage</p>
            {priceDeltaPct > 0 ? (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                Average price {formatINR(market.avgPrice)}/kg — about {priceDeltaPct}% below other nearby markets.
              </p>
            ) : priceDeltaPct < 0 ? (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                Average price {formatINR(market.avgPrice)}/kg — about {Math.abs(priceDeltaPct)}% above other nearby markets.
              </p>
            ) : (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                Average price {formatINR(market.avgPrice)}/kg — in line with other nearby markets.
              </p>
            )}
          </div>

          <div className="space-y-3">
            <div className="w-12 h-12 rounded-full bg-agri-50 text-agri-600 flex items-center justify-center">
              <Leaf size={20} />
            </div>
            <p className="mono-label text-neutral-400">Freshness Advantage</p>
            {freshnessRank === 1 ? (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                Freshest stock nearby — {market.avgFreshness}% average freshness, higher than any other nearby market.
              </p>
            ) : (
              <p className="text-base font-bold text-neutral-700 leading-relaxed">
                {market.avgFreshness}% average freshness — the {ordinal(freshnessRank)} freshest among {allMarkets.length} nearby markets.
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

function ordinal(n: number): string {
  const s = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}

export default RecommendedMarketSummary;
